DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE(id BIGINT PRIMARY KEY, name VARCHAR(255), description VARCHAR(255));
--
-- DROP TABLE IF EXISTS AUTHOR;
-- CREATE TABLE AUTHOR(id BIGINT PRIMARY KEY, name VARCHAR(255), FOREIGN KEY (id) REFERENCES GENRE (id), age INTEGER);
--
-- DROP TABLE IF EXISTS BOOK;
-- CREATE TABLE BOOK(id BIGINT PRIMARY KEY, name VARCHAR(255), page INTEGER, FOREIGN KEY (author) REFERENCES AUTHOR (id) , FOREIGN KEY (genre) REFERENCES GENRE (id));
