DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK(ID BIGINT PRIMARY KEY, NAME VARCHAR(255), PAGE INTEGER, AUTHOR INTEGER, GENRE INTEGER);

DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE(ID BIGINT PRIMARY KEY, NAME VARCHAR(255), DESCRIPTION VARCHAR(255));

DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR(ID BIGINT PRIMARY KEY, NAME VARCHAR(255), GENRE INTEGER, AGE INTEGER);
