DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK( id BIGINT PRIMARY KEY, name VARCHAR(255), page INTEGER, author_id BIGINT, genre_id BIGINT);
alter table BOOK ADD FOREIGN KEY (genre_id) REFERENCES GENRE(id);
alter table BOOK ADD FOREIGN KEY (author_id) REFERENCES AUTHOR(id);